version: "3"

services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        volumes:
            - "./frontend:/app"
        ports:
            - "3000:3000"
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes:
            - type: bind
              source: ./backend
              target: /var/www/html
        ports:
            - "8080:80"
    malicious:
        image: httpd
        volumes:
            - "./malicious:/usr/local/apache2/htdocs/"
        ports:
            - "8081:80"
